# Basics of tensor

In [1]:
import tensorflow as tf

In [52]:
tf.Tensor

tensorflow.python.ops.tensor_array_ops.TensorArray

In [68]:
x=tf.constant([[1,2,3,4],[5,6,7,8]],dtype="float32")

In [87]:
x

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)>

In [28]:
print(tf.is_tensor(x))

True

In [29]:
x.shape

TensorShape([2, 4])

In [26]:
y=[1,2,3,4]

In [37]:
x.dtype

tf.uint32

In [27]:
tf.is_tensor(y)

False

In [45]:
def seperator(length:int=45):
    print("-"*length)

In [51]:
print(f"Adding two tensors \n{x + x}")
seperator()
print(f"Multiplying two tensors \n{x * x}")
seperator()
print(f"Dividing two tensors \n{x // x}")
seperator()
print(f"Modulus two tensors \n{x % x}")
seperator()
print(f"Multiplying a tensor with a number \n{6 * x}")

Adding two tensors 
[[ 2  4  6  8]
 [10 12 14 16]]
---------------------------------------------
Multiplying two tensors 
[[ 1  4  9 16]
 [25 36 49 64]]
---------------------------------------------
Dividing two tensors 
[[1 1 1 1]
 [1 1 1 1]]
---------------------------------------------
Modulus two tensors 
[[0 0 0 0]
 [0 0 0 0]]
---------------------------------------------
Multiplying a tensor with a number 
[[ 6 12 18 24]
 [30 36 42 48]]


In [62]:
print(f"Transpose of x \n{tf.transpose(x)}")
seperator()
print(f"Concatenation (axis=0)\n {tf.concat([x,x],axis=0)}")
seperator()
print(f"Concatenation (axis=1)\n {tf.concat([x,x],axis=1)}")

Transpose of x 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
---------------------------------------------
Concatenation (axis=0)
 [[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
---------------------------------------------
Concatenation (axis=1)
 [[1 2 3 4 1 2 3 4]
 [5 6 7 8 5 6 7 8]]


<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)>

In [86]:
print(f"Soft max activation function\n{tf.nn.softmax(x,axis=-1)}")
seperator()
print(f"Sum of softmax activation function values\n{sum(tf.nn.softmax(x,axis=-1)[0])}") # Approx 1

Soft max activation function
[[0.0320586  0.08714432 0.2368828  0.6439142 ]
 [0.0320586  0.08714432 0.2368828  0.6439142 ]]
---------------------------------------------
Sum of softmax activation function values
0.9999999403953552


In [90]:
print(f"Sigmoid activation function\n{tf.nn.sigmoid(x)}")

Sigmoid activation function
[[0.7310586  0.8807971  0.95257413 0.98201376]
 [0.9933072  0.99752736 0.99908894 0.99966466]]


In [109]:
print(f"Sum of all values \n{tf.reduce_sum(x)}")
seperator()
print(f"Average of all values \n{tf.reduce_mean(x)}")
seperator()
print(f"AND operation on boolean values \n{tf.reduce_all([True,False])}") # Logical and
seperator()
print(f"OR operation on boolean values \n{tf.reduce_any([True,False])}") # Logical and
seperator()
print(f"Maximum of all values \n{tf.reduce_max(x)}") # Maximum value
seperator()
print(f"Product of all values \n{tf.reduce_prod(x)}") # Multiplies all value

Sum of all values 
36.0
---------------------------------------------
Average of all values 
4.5
---------------------------------------------
AND operation on boolean values 
False
---------------------------------------------
OR operation on boolean values 
True
---------------------------------------------
Maximum of all values 
8.0
---------------------------------------------
Product of all values 
40320.0


In [117]:
if tf.config.list_physical_devices('GPU'):
  print("TensorFlow **IS** using the GPU")
else:
  print("TensorFlow **IS NOT** using the GPU")

TensorFlow **IS NOT** using the GPU


In [119]:
import tensorflow as tf
print(tf.test.is_built_with_cuda())

False
